name = "Arda"
author = "Taffer, Roboat et al."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26fedce01dca4866e78030edb49c5f2796c724ddabf14a3d751c5493cfc3a24e"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
