name = "Arda"
author = "Taffer, Roboat et al."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c8fbddaf62ce7864f2a47e61fbc2650a3296820e0406badae1c666af75fb81"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
