name = "Arda"
author = "Taffer, Roboat et al."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2d1532845d51b1fad62af7fdf219efadc919142c9de8d8103496bc14bd7c4dd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
