#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Mar 05 17:48:58 EST 2026
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
